### ISSUE TITLE
Dev - Add new props to product model

### ISSUE THREAD

**Issue by Ateto1204** [we-we-Web/shopping-platform-backend#12]

**Comment by Ateto1204** [comment]
Please add the comments of props that you're going to create, thx.

**Comment by tyuLD** [comment]
前端的需求
商品:
name
price 
description 
categories 
discount
quantity_remain 要分size(S,M,L,XL)
quantity_sold
sales time 上架時間
rating
review

**Comment by Ateto1204** [comment]
請前端 PO 要把 props 項目定義清楚，比如說 description 是什麼，
另外後端應該已經有提供 name props 了，你們要確認一下是不是他們叫別的名字，
比如說 title 之類的。

**Comment by 01257158** [comment]
第一部分：description , categories , discount

**Comment by 01257158** [comment]
第二部分：quantity_sold , sales_time , rating , review
